# Generated by Django 5.0.4 on 2024-05-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurantdomain_restaurant_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_lat',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_long',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
