# Generated by Django 5.0.4 on 2024-05-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_restaurant_lat_restaurant_restaurant_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantdomain',
            options={'verbose_name_plural': 'restaurants domains'},
        ),
    ]
