# Generated by Django 5.0.4 on 2024-05-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_dish_category_dish_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AddField(
            model_name='dish',
            name='note',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='number_of_review',
            field=models.IntegerField(default=0),
        ),
    ]
