# Generated by Django 5.0.4 on 2024-05-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_category_options_alter_dish_options_dish_note_and_more'),
        ('orders', '0005_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='menu.dish'),
            preserve_default=False,
        ),
    ]
